#!/bin/sh
# Migration 22 --> 23

set -euo pipefail

kubectl delete hr -n cozy-fluxcd fluxcd --ignore-not-found

# Stamp version
kubectl create configmap -n cozy-system cozystack-version \
  --from-literal=version=23 --dry-run=client -o yaml | kubectl apply -f-
